frontend/__init__.py
from flask import Blueprint

frontend_bp = Blueprint(
    "frontend_bp",
    __name__,
    template_folder="templates",
    static_folder="static",
    url_prefix="",
)
from frontend import views

frontend/views.py
import os
import logging
from flask import render_template
from frontend import frontend_bp as bp
from runserver import SCOPE_ADMIN as admin

# service_tags = admin.registered_internal_service_tags
ext_services = admin.external_service_infos


LOGGER = logging.getLogger("scope-admin")


@bp.route("/")
@bp.route("/index")
def index():
    """index route

    Returns:
        html: page / dashboard of scope-admin
    """
    # try:
    service_tags = admin.registered_internal_service_tags

    status = admin.check_status_of_services()

    return render_template(
        "index.html",
        service_tags=service_tags,
        status=status,
        ext_services=ext_services,
    )
    # except Exception as e:
    #     return f"No Docker Client found. Start your Docker Client! {e}"


@bp.route("/service/<tag>")
def service(tag):
    """service route

    Args:
        tag (str): tag of service

    Returns:
        html: page of service, show information, config file, status, logs, etc
    """
    config = ""
    service_tags = admin.registered_internal_service_tags
    try:
        service_instance = admin.get_service_with_tag(tag)
        config = service_instance.config
        if not service_instance.container:
            LOGGER.warning(f"Currently no container for {tag}.")
            status = "no container"
            logs = ""
            if not config:
                config = ""
        status = service_instance.running
        try:
            logs = service_instance.logs.decode("UTF 8")
        except Exception as e:
            LOGGER.warning(f"Currently no logs for {tag}. {e}")
            logs = ""
    except Exception as e:
        LOGGER.warning(f"Currently no container for {tag}. {e}")
        status = "no container"
        logs = ""
        if not config:
            config = ""

    return render_template(
        "service.html",
        service_tags=service_tags,
        tag=tag,
        config=config,
        logs=logs,
        status=status,
        ext_services=ext_services,
    )


@bp.route("/webinterface/<tag>")
def webinterface(tag):
    """webinterface route

    Args:
        tag (str): tag of service

    Returns:
        html: page of webinterface of service inside a iframe
    """
    service_tags = admin.registered_internal_service_tags
    service_instance = admin.get_service_with_tag(tag)
    start = service_instance.config["start-page"]
    if os.environ["MODE"] == "PRODUCTION":
        domain = "https://" + os.environ["DOMAIN"]
    else:
        domain = "http://localhost"

    return render_template(
        "webinterface.html",
        service_tags=service_tags,
        domain=domain,
        tag=tag,
        start=start,
        ext_services=ext_services,
    )


@bp.route("/service_external/<tag>")
def service_external(tag):
    """service_external route

    Args:
        tag (str): tag of service

    Returns:
        html: page of external service
    """
    service_tags = admin.registered_internal_service_tags

    return render_template(
        "service-external.html",
        service_tags=service_tags,
        tag=tag,
        ext_services=ext_services,
    )


@bp.route("/registration")
def registration():
    """registration route

    Returns:
        html: page for registration of a new service
    """
    service_tags = admin.registered_internal_service_tags

    return render_template(
        "service-registration.html",
        service_tags=service_tags,
        ext_services=ext_services,
    )

frontend/templates/index.html
{% extends "layout.html" %}
{{ super() }}
{% block title %}SCOPE - Dashboard{% endblock %}
{% block subtitle %}Dashboard{% endblock %}

{% block content %}

<!-- Active Services -->
<h1 class="h4 mb-2 text-gray-800">Active Services</h1>

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5">
  {% for key, value in status.items() %}
  <div class="col mb-4 d-flex align-items-stretch">
    <div class="card  mx-auto" style="width: 18rem;">
      <div class="card-body d-flex flex-column">
        <h5 class="card-title">{{value[2]}}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          {% if value[0] %}
          <span class="running">Active</span>
          {% else %}
          <span class="stopped">Stopped</span>
          {% endif %}
        </h6>
        <p class="card-text mt-2">{{value[1]}}</p>
        <a type="button" href="/service/{{key}}" class="btn btn-outline-primary mt-auto">Go To</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>


<!-- External Services -->
<h1 class="h4 mb-2 text-gray-800 mt-4">External Services</h1>

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5">
  {% for servicetag, servicevalues in ext_services.items() %}
  <div class="col mb-4 d-flex align-items-stretch">
    <div class="card  mx-auto" style="width: 18rem;">
      <div class="card-body d-flex flex-column">
        <h5 class="card-title">
          <p>{{servicevalues["name"]}}
        </h5>
        <h6 class="card-subtitle mb-2 text-muted">

        </h6>
        <p class="card-text mt-2">{{servicevalues["description"]}}</p>
        <a type="button" href="/service_external/{{servicetag}}" class="btn btn-outline-primary mt-auto">Go To</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>





{% endblock %}

frontend/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Projekt Scope">
  <link rel="icon" type="image/png" sizes="32x32"
    href="{{ url_for('frontend_bp.static', filename='favicon-32x32.png') }}">

  <link rel="shortcut icon" href="{{ url_for('frontend_bp.static', filename='favicon.ico') }}">

  <title>{% block title %}{% endblock %}</title>

  <!-- Custom fonts for this template -->
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <!-- Custom styles for this template -->
  <link rel="stylesheet" type="text/css" href="{{ url_for('frontend_bp.static', filename='css/sb-admin-2.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('frontend_bp.static', filename='css/service.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('frontend_bp.static', filename='css/main.css') }}">

  <!-- Codemirror -->
  <link rel="stylesheet" href="{{ url_for('frontend_bp.static', filename='codemirror/lib/codemirror.css') }}">
  <script src="{{ url_for('frontend_bp.static', filename='codemirror/lib/codemirror.js') }}"></script>
  <script src="{{ url_for('frontend_bp.static', filename='codemirror/addon/edit/matchbrackets.js') }}"></script>
  <script src="{{ url_for('frontend_bp.static', filename='codemirror/mode/javascript/javascript.js') }}"></script>
  <script src="{{ url_for('frontend_bp.static', filename='codemirror/addon/display/autorefresh.js') }}"></script>


  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
  </script>

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" style="  background-color: rgb(255, 255, 255);
      " href="/">
        <div class="sidebar-brand-icon rotate-n-15">
          <img src="{{ url_for('frontend_bp.static', filename='img/scope_logo_512.png') }}" width="50px">
        </div>
        <div class="sidebar-brand-text text-dark mx-3">SCOPE Data Service</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="/">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- INTERNAL SERVICES -->
      <div class="sidebar-heading">Services</div>
      {% for tag in service_tags %}
      <li class="nav-item">
        <a class="nav-link collapsed" href="{{ url_for('frontend_bp.service', tag=tag) }}">
          <i class="fas fa-cog"></i>
          <span>{{tag}} </span>
        </a>
      </li>
      {% endfor %}

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- EXTERNAL SERIVCES-->
      <div class="sidebar-heading">External Services</div>
      {% if ext_services %}
      {% for servicetag, servicevalues in ext_services.items() %}
      <li class="nav-item">
        <a class="nav-link collapsed" href="/service_external/{{servicetag}}">
          <i class="fas fa-cog"></i>
          <span>{{servicetag}} </span>
        </a>
      </li>
      {% endfor %}
      {% endif%}

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">
      <div class="sidebar-heading">Service Registration</div>

      <li class="nav-item">
        <a class="nav-link collapsed" href="{{ url_for('frontend_bp.registration') }}">
          <i class="fas fa-cog"></i>
          <span>Registration </span>
        </a>
      </li>



      <!-- Sidebar Toggler -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content  Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Content  -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">
            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Admin</span>
                <!--<img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">-->
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>
          </ul>
        </nav>
        <!-- End of Topbar -->


        <!-- Begin Main Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">{% block subtitle %}{% endblock %}</h1>
          </div>

          {% block content %}{% endblock %}
        </div> <!-- End of Main Content -->
      </div> <!-- End of Content Wrapper -->
    </div> <!-- End of Page Wrapper -->


    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>


    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
      aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="login.html">Logout</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="loader"></div>
  <script src="{{url_for('frontend_bp.static', filename='js/navbar-functions.js')}}"></script>

</body>

</html>

frontend/templates/service-external.html
{% extends "layout.html" %}
{{ super() }}
{% block title %}SCOPE - Dashboard{% endblock %}
{% block subtitle %}EXTERNAL SERVICE{% endblock %}
{% block content %}
Work in progress...

{% endblock %}

frontend/templates/service-registration.html
{% extends "layout.html" %}
{{ super() }}
{% block title %}SCOPE - Dashboard{% endblock %}
{% block subtitle %}Dashboard{% endblock %}

{% block content %}

<h1 class="h4 mb-2 text-gray-800">Register new service with git</h1>
<div style="padding-bottom: 1%;">
  <input size="70" placeholder="git url" no-label-float="" tabindex="0" aria-disabled="false" id="git_url"
    value="https://oauth2:token@gitlab.itc-engineering.com/scope/teddy-service.git"></input>
</div>

<a href="javascript:void(0)" class="btn btn-sm btn-primary shadow-sm" id="register"><i
    class="fas fa-hammer fa-sm text-white-50"></i>&nbsp;&nbsp;Register</a>

<p>&nbsp;</p>

<script>
  url_register = "{{ url_for('api_bp.api_register_service') }}";
</script>
<script src="{{ url_for('frontend_bp.static', filename='js/register-functions.js') }}"></script>


{% endblock %}

frontend/templates/service.html
{% extends "layout.html" %}
{{ super() }}
{% block title %}SCOPE - Dashboard{% endblock %}
{% block subtitle %}
{% if config %}
  {% if status==True %}
    <i class="fas fa-circle fa-sm status-running" id="status"></i>
  {% else %}
    <i class="fas fa-circle fa-sm status-stop" id="status"></i>
  {% endif %}
  {{config["name"]}}
  {% else %}
  The {{tag}}-folder was not found in the scope-admin file tree. You have to add this folder with a correct config.json manually or by using the git registration.
  {% endif %}

  {% endblock %}

{% block content %}
{% if config %}
<div id="buttons-options">
  <a href="javascript:void(0)" class="btn btn-sm btn-primary shadow-sm" id="build"><i
      class="fas fa-hammer fa-sm text-white-50"></i>&nbsp;&nbsp;Install</a>
  <a href="javascript:void(0)" class="btn btn-sm btn-primary shadow-sm" id="uninstall"><i
      class="fas fa-trash fa-sm text-white-50"></i>&nbsp;&nbsp;Uninstall</a>
  <a href="javascript:void(0)" class="btn btn-sm btn-primary shadow-sm" id="restart"><i
      class="fas fa-play fa-sm text-white-50" id="restart-icon"></i>
  <div id="restart-text" style="display:inline;">&nbsp;&nbsp;Start</div>
  </a>
  <a href="javascript:void(0)" class="btn btn-sm btn-primary shadow-sm" id="stop"><i
      class="fas fa-stop fa-sm text-white-50"></i>&nbsp;&nbsp;Stop</a>
</div>


<div id="button-webinterface">
  <a href="/../webinterface/{{tag}}"
    class="btn btn-sm btn-primary shadow-sm" id="web"><i
      class="fas fa-window-maximize fa-sm text-white-50"></i>&nbsp;&nbsp;Webinterface</a>
</div>


<p id="description">
  {{config["description"]}}
</p>

<h1 class="h4 mb-2 text-gray-800"> Config </h1>
<textarea id="service-config" class="service-config" style="height:auto;">{{config["environment"]|tojson}}</textarea>
<!-- <textarea>{{config["environment_backup"]}}</textarea> -->
<div class="buttons-config">
  <a href="javascript:void(0)" class="btn btn-sm btn-primary shadow-sm" id="save-config"><i
      class="fas fa-save fa-sm text-white-50"></i>&nbsp;&nbsp;Save</a>
  <a href="javascript:void(0)" class="btn btn-sm btn-primary shadow-sm" id="restore-config"><i
      class="fas fa-trash-restore fa-sm text-white-50"></i>&nbsp;&nbsp;Restore</a>
</div>

<h1 class="h4 mb-2 text-gray-800"> Ports </h1>
<div class="buttons-config">

  <table>
    <tbody>
      <tr>
        <th>Container</th>
        <th>Host</th>
        <th>Description</th>
      </tr>
      <!---->
      {% for key, value in config["ports"].items() %}
      <tr>
        <td id="container_port">
          <!---->{{key}}
          <!---->
        </td>
        <td>
          <input placeholder="{{value}}" no-label-float="" tabindex="0" aria-disabled="false" id="port"></input>
        </td>
        <td>
          Interface
        </td>

      </tr>

      {% endfor %}
      <!---->
    </tbody>
  </table>
</div>
<div class="buttons-config">
  <a href="javascript:void(0)" class="btn btn-sm btn-primary shadow-sm" id="save-port"><i
      class="fas fa-save fa-sm text-white-50"></i>&nbsp;&nbsp;Save</a>
</div>


<h1 class="h4 mb-2 text-gray-800"> Logs </h1>
<textarea id="service-logs">{{logs}}</textarea>
<div class="buttons-config">
  <a href="javascript:void(0)" class="btn btn-sm btn-primary shadow-sm" id="refresh-logs"><i
      class="fas fa-redo fa-sm text-white-50"></i>&nbsp;&nbsp;Refresh</a>
</div>

{% endif %}
<script>
  url = "{{ url_for('api_bp.api_service') }}";
  url_config = "{{ url_for('api_bp.api_service_config') }}";
  url_port = "{{ url_for('api_bp.api_service_port') }}";
  tag = "{{ config["tag"] }}";
  {% if config %}
  // restore_config_text = "{{config["environment_backup"] | tojson}}";
  {% endif %}
</script>

<script src="{{ url_for('frontend_bp.static', filename='js/service-functions.js') }}"></script>

{% endblock %}

frontend/templates/webinterface.html
{% extends "layout.html" %}
{{ super() }}
{% block title %}SCOPE - Dashboard{% endblock %}

{% block content %}

<div class="embed-responsive embed-responsive-16by9 embed-container">
    <iframe src="{{domain}}/{{tag}}{{start}}" frameborder="0"></iframe>
</div>


<script>
    // Find all iframes
    var $iframes = $("iframe");

    // Resize the iframes when the window is resized
    $(window).resize(function () {
        $iframes.each(function () {
            // Get the parent containers width
            var width = $(this).parent().width();
            $(this).width(width)
                .height(width * $(this).data("ratio"));
        });
        // Resize to fix all iframes on page load.
    }).resize();
</script>
{% endblock %}